### PR TITLE
Created a couple of new routes to quickly serve live data and test...

### PR DESCRIPTION
**Pull request by austiezr**
connection to database.

Updated .gitignore and reqs.

Renamed folder for api to remove identifier from previous cohort.

Created a dockerfile preparatory to deploying to elasticbeanstalk.

Didn't succesfully deploy to elasticbeanstalk.

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [X] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [X] Was testing concurrently with jon testing the database; was able to briefly serve live data from the db.
- [ ] Test B

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by austiezr** [comment]
Tested new daily historical endpoint by giving it today's date; works as expected, after midnight we'll know for sure.

**Review by jonDuke — COMMENTED** [review]
your requirements.txt change undoes that bleach version bump, probably want to leave that on 3.1.4

**Comment by austiezr** [comment]
Noted and fixed, thanks!

**Comment by austiezr** [comment]
@jonDuke json routes fixed! Tested locally.

**Pull request merged**
